version: "3"
services:
  mypython:
    build: .
    volumes:
      - "./:/usr/src/app/"
  selenium-hub:
    restart: always
    image: selenium/hub
    ports:
      - 4444:4444
      - 4443:4443
      - 4442:4442

  node_1:
    image: selenium/node-chrome:4.1.2-20220217
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

# version: "3"
# services:
#   mypython:
#     build: .
#   selenium-hub:
#     restart: always
#     image: selenium/hub:3.141.59
#     environment:
#       GRID_BROWSER_TIMEOUT: 0
#       GRID_TIMEOUT: 0
#     ports:
#       - 4444:4444
#   selenium-node:
#     restart: always
#     image: selenium/node-chrome:latest
#     stdin_open: true
#     depends_on:
#       - selenium-hub
#     links:
#       - selenium-hub
#     environment:
#       SE_EVENT_BUS_HOST: selenium-hub
#       SE_EVENT_BUS_PUBLISH_PORT: 4442
#       SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
#       JAVA_OPTS: -Xmx1024m
#       DBUS_SESSION_BUS_ADDRESS: /dev/null
#       HUB_PORT_4444_TCP_ADDR: selenium-hub
#       HUB_PORT_4444_TCP_PORT: 4444
#       no_proxy: localhost
#       START_XVFB: "true"
#     shm_size: "2gb"






#   mariadb:
#     image: docker.io/bitnami/mariadb:10.3
#     environment:
#       # ALLOW_EMPTY_PASSWORD is recommended only for development.
#       - ALLOW_EMPTY_PASSWORD=yes
#       - MARIADB_USER=bn_testlink
#       - MARIADB_DATABASE=bitnami_testlink
#     volumes:
#       - 'mariadb_data:/bitnami/mariadb'
#   testlink:
#     build: .
#     ports:
#       - '80:8080'
#       - '443:8443'
#     environment:
#       - TESTLINK_DATABASE_HOST=mariadb
#       - TESTLINK_DATABASE_PORT_NUMBER=3306
#       - TESTLINK_DATABASE_USER=bn_testlink
#       - TESTLINK_DATABASE_NAME=python_image
#       # ALLOW_EMPTY_PASSWORD is recommended only for development.
#       - ALLOW_EMPTY_PASSWORD=yes
#     volumes:
#       - 'testlink_data:/bitnami/testlink'
#     depends_on:
#       - mariadb
# volumes:
#   mariadb_data:
#   testlink_data:

